export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const SET_INGREDIENT = "SET_INGREDIENT";
export const FETCH_FAILED = "FETCH_FAILED";

export const PURCHASE_FAILED = 'PURCHASE_FAILED';
export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_START = "PURCHASE_START";
export const INIT_PURCHASE = 'INIT_PURCHASE';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REDIRECT = 'AUTH_REDIRECT'